### PR TITLE
A function to make single cell summary plots

### PR DESCRIPTION
**Pull request by dougollerenshaw**
Example use:

```python
from visual_behavior.visualization.qc import single_cell_across_experiments as scae
scae.make_single_cell_across_experiment_plot(cell_specimen_id, glm_version)
```
Generates a plot that looks like this:
image

### CODE REVIEW

**Comment by alexpiet** [comment]
We had discussed adding the model predictions overlaid on top of the event triggered average. Is that still on the table?

**Comment by dougollerenshaw** [comment]
@alexpiet, yes, it could be.

The kernels will not necessarily match the xlims for the event triggered average plots. For example, for the individual images, the kernel is only 750 ms long, but I'm plotting 4 seconds of event triggered average. Think that'll be weird?

**Comment by alexpiet** [comment]
So you could plot the kernels, which I think was my original suggestion. Or you could use the full session trace and compute the event triggered averages of the model. That way it will have the same dimensions as the data

**Comment by dougollerenshaw** [comment]
I like those ideas. I will try both.

**Comment by dougollerenshaw** [comment]
This PR is dated, but I'm not going to be able to work on it further. I'm force-merging to master.

**Pull request merged**
