### PR TITLE
removing sdk_translator

### PR DESCRIPTION
**Pull request by alexpiet**
@matchings @dougollerenshaw @DowntonCrabby @yavorska-iryna @farznaj 

To my knowledge, the only code that was using the `translator/allensdk_translator/` functions were the behavior model, which I have just updated to use the `loading/data_access` functions. Rather than maintaining these old functions, I propose removing them. Any objections?

### CODE REVIEW

**Review by dougollerenshaw — APPROVED** [review]
Makes sense to remove.

**Comment by dougollerenshaw** [comment]
@alexpiet there are tests associated with the module that are now failing. See `tests/translator/allensdk_sessions/test_allendk_session_translation.py`

**Comment by dougollerenshaw** [comment]
I recently added instructions for running tests locally to the project README. That'll let you run the same tests on your local machine that CircleCI will run on the cloud. That way you can make sure everything passes without having to commit and wait for the CircleCI tests.

**Comment by alexpiet** [comment]
> @alexpiet there are tests associated with the module that are now failing. See `tests/translator/allensdk_sessions/test_allendk_session_translation.py`

I dont understand how a test can fail if we are removing the functions?

**Comment by dougollerenshaw** [comment]
There is a test on the module that fails because it can't import the module:
https://github.com/AllenInstitute/visual_behavior_analysis/blob/814a222aa51fb421375fbb110cb8c04893b98954/tests/translator/allensdk_sessions/test_allendk_session_translation.py#L5

It seems to me that this entire folder should be removed as part of this PR:
https://github.com/AllenInstitute/visual_behavior_analysis/tree/remove_sdk_translator/tests/translator/allensdk_sessions

**Comment by alexpiet** [comment]
ugh, I thought I *did* remove the entire folder. I do not understand the circleci tests at all.

**Comment by dougollerenshaw** [comment]
All passing now. Thanks! I'll merge.

**Pull request merged**
